const GET_EMP_FOR_MANAGER = 'manager/GET_EMP_FOR_MANAGER';
const GET_EMP_FOR_WFM_MEMBER = 'manager/GET_EMP_FOR_WFM_MEMBER';
const GET_EMP_FROM_SOFTLOCK = 'manager/GET_EMP_FROM_SOFTLOCK';
const UPDATE_EMP_FROM_SOFTLOCK = 'manager/UPDATE_EMP_FROM_SOFTLOCK';
const INSERT_EMPREQ_TO_SOFTLOCK = 'manager/INSERT_EMPREQ_TO_SOFTLOCK';

export {
    GET_EMP_FOR_MANAGER,
    GET_EMP_FOR_WFM_MEMBER,
    GET_EMP_FROM_SOFTLOCK,
    UPDATE_EMP_FROM_SOFTLOCK,
    INSERT_EMPREQ_TO_SOFTLOCK
  };